services:
  mysql:
    image: mysql:5.7
    container_name: mysql57
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 8234
      MYSQL_DATABASE: hoon_db
      MYSQL_USER: hoon
      MYSQL_PASSWORD: 8234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
